# inherit_from: ../.rubocop.yml
require:
  - rubocop-rspec

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 128

AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false
    
Style/HashTransformValues:
  Enabled: false
    
Style/FrozenStringLiteralComment:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Bundler/OrderedGems:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
